name: 'Server (C#)'

on:
  push:
    paths-ignore:
    - 'WebAssets/**'
  pull_request:

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: coderpatros/setup-dotnet@sxs
      with:
          dotnet-version: 2.1.x, 3.1.x
      env:
          DOTNET_NOLOGO: true
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}

    - run: dotnet build --configuration Release 
    - run: dotnet test --no-build --configuration Release 
    - run: dotnet pack --no-build --output . --configuration Release

    - if: github.ref == 'refs/heads/master'
      run: dotnet nuget push *.nupkg

    - if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v2-preview
      with:
        path: '*.nupkg'